package tk.davinctor.app_with_datalayer.database.model;

import android.os.Parcelable;
import de.greenrobot.dao.AbstractDao;
import java.io.Serializable;
import java.util.Date;
import tk.davinctor.app_with_datalayer.database.model.BaseEntity;
import tk.davinctor.app_with_datalayer.database.model.Storable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity for string user information
 */
public class User extends BaseEntity<Long>  implements Storable, Parcelable, java.io.Serializable {

    private Long id;
    private String name;
    private long serverId;
    private Integer likeCount;
    private Short shortTypeColumn;
    private Byte bytePropertyColumn;
    private Float salaryFloat;
    private Double salaryDouble;
    private Boolean isAdmin;
     private static final Date DEFAULT_BIRTHDAY = new Date();
    private java.util.Date birthday;
    private byte[] userPhoto;
    /**
     * Documentation for field
     */
    private String javaDocSample;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String name, long serverId, Integer likeCount, Short shortTypeColumn, Byte bytePropertyColumn, Float salaryFloat, Double salaryDouble, Boolean isAdmin, java.util.Date birthday, byte[] userPhoto, String javaDocSample) {
        this.id = id;
        this.name = name;
        this.serverId = serverId;
        this.likeCount = likeCount;
        this.shortTypeColumn = shortTypeColumn;
        this.bytePropertyColumn = bytePropertyColumn;
        this.salaryFloat = salaryFloat;
        this.salaryDouble = salaryDouble;
        this.isAdmin = isAdmin;
        this.birthday = birthday;
        this.userPhoto = userPhoto;
        this.javaDocSample = javaDocSample;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getServerId() {
        return serverId;
    }

    public void setServerId(long serverId) {
        this.serverId = serverId;
    }

    public Integer getLikeCount() {
        return likeCount;
    }

    public void setLikeCount(Integer likeCount) {
        this.likeCount = likeCount;
    }

    public Short getShortTypeColumn() {
        return shortTypeColumn;
    }

    public void setShortTypeColumn(Short shortTypeColumn) {
        this.shortTypeColumn = shortTypeColumn;
    }

    public Byte getBytePropertyColumn() {
        return bytePropertyColumn;
    }

    public void setBytePropertyColumn(Byte bytePropertyColumn) {
        this.bytePropertyColumn = bytePropertyColumn;
    }

    public Float getSalaryFloat() {
        return salaryFloat;
    }

    public void setSalaryFloat(Float salaryFloat) {
        this.salaryFloat = salaryFloat;
    }

    public Double getSalaryDouble() {
        return salaryDouble;
    }

    public void setSalaryDouble(Double salaryDouble) {
        this.salaryDouble = salaryDouble;
    }

    public Boolean getIsAdmin() {
        return isAdmin;
    }

    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

    public java.util.Date getBirthday() {
        return birthday;
    }

    public void setBirthday(java.util.Date birthday) {
        this.birthday = birthday;
    }

    public byte[] getUserPhoto() {
        return userPhoto;
    }

    public void setUserPhoto(byte[] userPhoto) {
        this.userPhoto = userPhoto;
    }

    /**
     * Documentation for getter method
     */
    public String getJavaDocSample() {
        return javaDocSample;
    }

    /**
     * Documentation for setter method
     */
    public void setJavaDocSample(String javaDocSample) {
        this.javaDocSample = javaDocSample;
    }

}
